### PR TITLE
BrijeshG_Assignment_29

### PR DESCRIPTION
**Pull request by BrijeshGOct2020**
image

### CODE REVIEW

**Review by harshvegada — CHANGES_REQUESTED** [review]
we can handle in single loop only right. in your case time complexity is 2n

check this code, I m sure you get my idea, please update code n acknowledge me.
https://github.com/KrishnaKTechnocredits/JAVATechnoOct2020/blob/main/src/nandini/SecondMaxNumber.java

**Comment by BrijeshGOct2020** [comment]
Hi @harshvegada 

Updated code. Handling negative and all corner cases as well. Thanks
image

**Comment by BrijeshGOct2020** [comment]
Hi @harshvegada,

Thanks
Updated code with all corner cases and negative number
image

**Review by harshvegada — APPROVED** [review]
Code looks good to me! 
very optimized code!
Good to merge

**Pull request merged**
