### PR TITLE
PrasadC_Assignment_25

### PR DESCRIPTION
**Pull request by PrasadCOct2020**
Hi Both,
Please review my PR.
image

Regards 
Prasad Chitale

### CODE REVIEW

**Comment by PrasadCOct2020** [comment]
Hi @harshvegada / @MaulikTechnocredits I will commit another class which does sum of whole numbers and not digits.

**Comment by PrasadCOct2020** [comment]
Hi @MaulikTechnocredits  I have added this condition else if(Character.isLetter(ch)|| !Character.isLetterOrDigit(ch)) 
for scenario when we have a number 100 which is followed by a space. In such case we will add the captured number to sum and make temp ="";

**Comment by PrasadCOct2020** [comment]
Eg: "I have 15 years and **100** 2 months of experience"

**Review by harshvegada — APPROVED** [review]
Very well prasad,
Code looks good to me!
Good to merge!

**Pull request merged**
